In [11]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
# se carga el dataset que se va a utilizar para dos dataframes distintos
data = pd.read_csv('data/merge_games.csv')
data_juegos_steam = pd.read_parquet('data/df_games.parquet')

In [6]:
data

,id,user_id,item_id,title,genres,developer,anio,price,recommend,year_posted,sentiment_analysis,playtime_forever
0,Bennysaputra10,Bennysaputra,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2015,1,24336
1,7656119804018806110,76561198040188061,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2011,2,3895
2,mayshowganmore10,mayshowganmore,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2014,1,10113
3,BestinTheWorldThund3r10,BestinTheWorldThund3r,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2014,2,264
4,7656119807220716210,76561198072207162,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2014,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...
31846,76561198069334653364510,76561198069334653,364510,Transcendence,"['Action', 'Indie', 'RPG']",Kronosaur Productions,2015,8.99,1,2015,0,302
31847,toottootverysad343000,toottootverysad,343000,The Mystery of the Druids,['Adventure'],House of Tales,2001,4.99,1,2015,2,8
31848,Kusaryuu370150,Kusaryuu,370150,LOOP: A Tranquil Puzzle Game,"['Casual', 'Indie']",John Cullen,2015,4.99,1,2015,2,985
31849,helenangel36150,helenangel,36150,Westward Collection,['Casual'],Sandlot Games,2009,14.99,1,2012,2,200
31850,kazanmor381850,kazanmor,381850,My Paper Boat,"['Adventure', 'Casual', 'Racing']",TML-Studios,2015,4.99,1,2015,1,48

In [7]:
data_juegos_steam

,genres,title,price,id,developer,anio
index,,,,,,
88310,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,4.99,761140,Kotoshiro,2018
88311,"[Free to Play, Indie, RPG, Strategy]",Ironbound,0.00,643980,Secret Level SRL,2018
88312,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,0.00,670290,Poolians.com,2017
88313,"[Action, Adventure, Casual]",å¼¹ç‚¸äºº2222,0.99,767400,å½¼å²¸é¢†åŸŸ,2017
88315,"[Action, Adventure, Simulation]",Battle Royale Trainer,3.99,772540,Trickjump Games Ltd,2018
...,...,...,...,...,...,...
120439,"[Action, Adventure, Casual, Indie]",Kebab it Up!,1.99,745400,Bidoniera Games,2018
120440,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,1.99,773640,"Nikita ""Ghost_RUS""",2018
120441,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,4.99,733530,Sacada,2018
120442,"[Indie, Racing, Simulation]",Russian Roads,1.99,610660,Laush Dmitriy Sergeevich,2018
120443,"[Casual, Indie]",EXIT 2 - Directions,4.99,658870,"xropi,stev3ns",2017

In [8]:
data_juegos_steam = data_juegos_steam.rename(columns={'id':'item_id'})

In [9]:
data

,id,user_id,item_id,title,genres,developer,anio,price,recommend,year_posted,sentiment_analysis,playtime_forever
0,Bennysaputra10,Bennysaputra,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2015,1,24336
1,7656119804018806110,76561198040188061,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2011,2,3895
2,mayshowganmore10,mayshowganmore,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2014,1,10113
3,BestinTheWorldThund3r10,BestinTheWorldThund3r,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2014,2,264
4,7656119807220716210,76561198072207162,10,Counter-Strike,['Action'],Valve,2000,9.99,1,2014,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...
31846,76561198069334653364510,76561198069334653,364510,Transcendence,"['Action', 'Indie', 'RPG']",Kronosaur Productions,2015,8.99,1,2015,0,302
31847,toottootverysad343000,toottootverysad,343000,The Mystery of the Druids,['Adventure'],House of Tales,2001,4.99,1,2015,2,8
31848,Kusaryuu370150,Kusaryuu,370150,LOOP: A Tranquil Puzzle Game,"['Casual', 'Indie']",John Cullen,2015,4.99,1,2015,2,985
31849,helenangel36150,helenangel,36150,Westward Collection,['Casual'],Sandlot Games,2009,14.99,1,2012,2,200
31850,kazanmor381850,kazanmor,381850,My Paper Boat,"['Adventure', 'Casual', 'Racing']",TML-Studios,2015,4.99,1,2015,1,48

In [10]:
# eliminando columnas irrelevantes
data_juegos_steam.drop(['genres','price','developer','anio'],axis=1,inplace=True)
data.drop(['id','user_id','genres','recommend','price','playtime_forever','year_posted','sentiment_analysis'],axis=1,inplace=True)

# cambiando tipos de datos
data['item_id'] = data['item_id'].astype(str)
data['anio'] = data['anio'].astype(str)

# borrando duplicados
data = data.drop_duplicates(subset='item_id', keep='first')
data_juegos_steam = data_juegos_steam.drop_duplicates(subset='item_id', keep='first')

# Combinar los valores de las columnas en una sola columna
data['features'] = data[['title', 'developer', 'anio']].apply(lambda x: ', '.join(x), axis=1)

data.drop(['title','developer','anio'],axis=1,inplace=True)

# Exportar data limpia de juegos
data.to_csv('juegos_steam.csv', index=False)
data_juegos_steam.to_csv('juegos_id.csv', index=False)

C:\Users\SimpleDeco\AppData\Local\Temp\ipykernel_24352\4009886088.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['features'] = data[['title', 'developer', 'anio']].apply(lambda x: ', '.join(x), axis=1)
C:\Users\SimpleDeco\AppData\Local\Temp\ipykernel_24352\4009886088.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(['title','developer','anio'],axis=1,inplace=True)

In [19]:
def recomendacion_juego(item_id):
    # se carga los datasets que se va a utilizar para dos dataframes distintos
    data = pd.read_csv('juegos_steam.csv')
    data_juegos_steam = pd.read_csv('juegos_id.csv')

    # crear una matriz de caracterÃ­sticas de los juegos
    tfidv = TfidfVectorizer(min_df=2, max_df=0.7, token_pattern=r'\b[a-zA-Z0-9]\w+\b')
    data_vector = tfidv.fit_transform(data['features'])

    data_vector_df = pd.DataFrame(data_vector.toarray(), index=data['item_id'], columns = tfidv.get_feature_names_out())

    # calcular la similitud coseno entre los juegos en la matriz de caracterÃ­sticas
    vector_similitud_coseno = cosine_similarity(data_vector_df.values)

    cos_sim_df = pd.DataFrame(vector_similitud_coseno, index=data_vector_df.index, columns=data_vector_df.index)

    juego_simil = cos_sim_df.loc[item_id]

    simil_ordenada = juego_simil.sort_values(ascending=False)
    resultado = simil_ordenada.head(6).reset_index()

    result_df = resultado.merge(data_juegos_steam, on='item_id',how='left')

    # La funciÃ³n devuelve una lista de los 6 juegos mÃ¡s similares al juego dado
    juego_title = data_juegos_steam[data_juegos_steam['item_id'] == item_id]['title'].values[0]

    # mensaje que indica el juego original y los juegos recomendados
    mensaje = f"{item_id} : {juego_title}:"

    result_dict = {
        'Juego': mensaje,
        'Juegos recomendados': result_df['title'][1:6].tolist()
    }

    return result_dict